import JSZip from 'jszip';
import { ExtractionResult } from '../types';

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadText(text: string, filename: string, mimeType = 'text/plain') {
  const blob = new Blob([text], { type: mimeType });
  downloadBlob(blob, filename);
}

/**
 * Standard project zip generator (HTML, CSS, JS, without fetching remote media binaries)
 */
export async function generateProjectZip(data: ExtractionResult): Promise<Blob> {
  const zip = new JSZip();

  // 1. Cleaned index.html linking to external style.css and app.js
  const cleanIndexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(data.title)}</title>
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
${data.cleanedBodyHtml}

  <script src="js/app.js"></script>
</body>
</html>`;

  zip.file('index.html', cleanIndexHtml);

  // 2. css/style.css
  const cssFolder = zip.folder('css');
  if (cssFolder) {
    cssFolder.file('style.css', data.unifiedCss || '/* No CSS extracted */');

    data.stylesheets.forEach((sheet, idx) => {
      const safeName = sheet.name.replace(/[^a-zA-Z0-9_.-]/g, '_') || `sheet-${idx + 1}.css`;
      cssFolder.file(`individual/${safeName}`, sheet.content);
    });
  }

  // 3. js/app.js
  const jsFolder = zip.folder('js');
  if (jsFolder) {
    jsFolder.file('app.js', data.unifiedJs || '// No JavaScript extracted');

    data.scripts.forEach((script, idx) => {
      const safeName = script.name.replace(/[^a-zA-Z0-9_.-]/g, '_') || `script-${idx + 1}.js`;
      jsFolder.file(`individual/${safeName}`, script.content);
    });
  }

  // 4. Standalone all-in-one HTML
  zip.file('standalone-bundle.html', data.reconstructedBundleHtml);

  // 5. README.md
  const readmeContent = `# ${data.title}

> Extracted via easywebsite on ${new Date(data.stats.extractedAt).toLocaleString()}
> Original source: [${data.finalUrl}](${data.finalUrl})

## Project Contents

- **\`index.html\`**: Main webpage markup linked to modular CSS and JS files.
- **\`css/style.css\`**: Combined and organized stylesheet with all extracted rules.
- **\`css/individual/\`**: Original individual CSS stylesheets from the source.
- **\`js/app.js\`**: Combined scripts and runtime logic.
- **\`js/individual/\`**: Original individual script files from the source.
- **\`standalone-bundle.html\`**: Completely self-contained single-file version with inlined assets.

## How to Run Locally

\`\`\`bash
# Using Python
python3 -m http.server 8000

# Using Node.js npx
npx serve .

# Or simply double-click index.html or standalone-bundle.html in your browser
\`\`\`

---
*Generated by easywebsite — The Precision Web Code Extractor*
`;

  zip.file('README.md', readmeContent);

  return await zip.generateAsync({ type: 'blob' });
}

/**
 * COMBINED BUILD:
 * Downloads ALL CSS, HTML, JavaScript AND actually fetches and downloads
 * all media (images, SVGs, and favicons) into a dedicated `media/` folder,
 * rewrites references in the HTML and CSS, and packages everything together into
 * an offline-ready bundle.
 */
export async function generateCombinedBuildZip(
  data: ExtractionResult,
  onProgress?: (message: string, percent: number) => void
): Promise<Blob> {
  const zip = new JSZip();
  onProgress?.('Initializing Combined Build workspace...', 5);

  const mediaFolder = zip.folder('media');
  const mediaMap = new Map<string, string>(); // originalUrl -> localPath (e.g. 'media/asset-1.png')

  // Identify valid media assets to download
  const validAssets = data.assets.filter((a) => a.url && a.url.startsWith('http'));
  const totalAssets = Math.min(validAssets.length, 40); // Cap at 40 to maintain fast generation

  let downloadedMediaCount = 0;

  for (let i = 0; i < totalAssets; i++) {
    const asset = validAssets[i];
    const assetIndex = i + 1;
    const progressPercent = Math.round(10 + (assetIndex / Math.max(totalAssets, 1)) * 60);
    onProgress?.(`Downloading media asset ${assetIndex} of ${totalAssets} (${asset.name})...`, progressPercent);

    try {
      const cleanFilename = `media_${assetIndex}_${asset.name.replace(/[^a-zA-Z0-9_.-]/g, '_')}`;
      const localRelPath = `media/${cleanFilename}`;

      const proxyUrl = `/api/proxy?url=${encodeURIComponent(asset.url)}`;
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 6000);

      const res = await fetch(proxyUrl, { signal: controller.signal });
      clearTimeout(timeoutId);

      if (res.ok) {
        const arrayBuf = await res.arrayBuffer();
        if (mediaFolder && arrayBuf.byteLength > 0) {
          mediaFolder.file(cleanFilename, arrayBuf);
          mediaMap.set(asset.url, localRelPath);
          if (asset.originalSrc && asset.originalSrc.startsWith('http')) {
            mediaMap.set(asset.originalSrc, localRelPath);
          }
          downloadedMediaCount++;
        }
      }
    } catch {
      // Gracefully continue with remaining media
    }
  }

  onProgress?.('Re-linking media paths and stitching Combined Build...', 75);

  // 1. Rewrite combined standalone HTML with local media references
  let combinedStandaloneHtml = data.reconstructedBundleHtml;
  mediaMap.forEach((localPath, originalUrl) => {
    combinedStandaloneHtml = combinedStandaloneHtml.split(originalUrl).join(localPath);
  });
  zip.file('combined-build.html', combinedStandaloneHtml);

  // 2. Clean index.html with local modular references
  let combinedIndexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(data.title)} - Combined Build</title>
  <link rel="stylesheet" href="css/combined.css">
</head>
<body>
${data.cleanedBodyHtml}

  <script src="js/combined.js"></script>
</body>
</html>`;

  mediaMap.forEach((localPath, originalUrl) => {
    combinedIndexHtml = combinedIndexHtml.split(originalUrl).join(localPath);
  });
  zip.file('index.html', combinedIndexHtml);

  // 3. Combined CSS (with relative paths to media folder)
  const cssFolder = zip.folder('css');
  if (cssFolder) {
    let rewrittenCss = data.unifiedCss;
    mediaMap.forEach((localPath, originalUrl) => {
      rewrittenCss = rewrittenCss.split(originalUrl).join(`../${localPath}`);
    });
    cssFolder.file('combined.css', rewrittenCss);
  }

  // 4. Combined JS
  const jsFolder = zip.folder('js');
  if (jsFolder) {
    jsFolder.file('combined.js', data.unifiedJs || '// Combined Build JavaScript');
  }

  // 5. Media Manifest
  const manifest = {
    title: data.title,
    sourceUrl: data.finalUrl,
    extractedAt: data.stats.extractedAt,
    buildType: 'Combined Build (HTML, CSS, JS, Media)',
    totalDiscoveredAssets: data.assets.length,
    downloadedMediaCount,
    mediaMap: Array.from(mediaMap.entries()).map(([original, local]) => ({
      originalUrl: original,
      localFile: local,
    })),
  };
  zip.file('media-manifest.json', JSON.stringify(manifest, null, 2));

  // 6. Comprehensive README
  const readme = `# ${data.title} — Combined Build

This is a complete, self-contained **Combined Build** packaged by easywebsite.
All components required to run this website completely offline are included:
HTML markup, unified CSS, unified JavaScript, and local media assets.

## Directory Structure

\`\`\`
combined-build/
├── index.html              <- Modular HTML linked to local css/, js/, and media/
├── combined-build.html     <- Single-file standalone build with inlined CSS & JS
├── media/                  <- All ${downloadedMediaCount} downloaded images, SVGs, and favicons
├── css/
│   └── combined.css        <- Full unified stylesheet
├── js/
│   └── combined.js         <- Full unified client scripts
├── media-manifest.json     <- Mapping between origin URLs and local filenames
└── README.md               <- Project documentation
\`\`\`

## Offline Execution

Open either \`combined-build.html\` or \`index.html\` in any web browser.
No active internet connection or external server is required.

---
*Created with easywebsite — The Precision Web Code & Asset Extraction Engine*
`;
  zip.file('README.md', readme);

  onProgress?.('Compressing ZIP archive...', 95);
  const blob = await zip.generateAsync({ type: 'blob' });
  onProgress?.('Combined Build complete!', 100);
  return blob;
}
